// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kwqvauffxzmldyruzdny.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt3cXZhdWZmeHptbGR5cnV6ZG55Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIyODg5MTQsImV4cCI6MjA3Nzg2NDkxNH0.ejK4gZvh-mZu0cyh5Yk5ViNVMt631OHIDDn8BCDT9t8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});